In [6]:
import pandas as pd
import numpy as np
from datetime import datetime
pd.options.mode.chained_assignment = None  # default='warn'

In [7]:
train = pd.read_csv('./train.csv')
feature = pd.read_csv('./features.csv')
test = pd.read_csv('./test.csv')
train['Date'] = pd.to_datetime(train['Date'])
train['Week'] = train['Date'].dt.week
feature['Date'] = pd.to_datetime(feature['Date'])

In [8]:
feature

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False
5,1,2010-03-12,57.79,2.667,NaN,NaN,NaN,NaN,NaN,211.380643,8.106,False
6,1,2010-03-19,54.58,2.720,NaN,NaN,NaN,NaN,NaN,211.215635,8.106,False
7,1,2010-03-26,51.45,2.732,NaN,NaN,NaN,NaN,NaN,211.018042,8.106,False
8,1,2010-04-02,62.27,2.719,NaN,NaN,NaN,NaN,NaN,210.820450,7.808,False
9,1,2010-04-09,65.86,2.770,NaN,NaN,NaN,NaN,NaN,210.622857,7.808,False
10,1,2010-04-16,66.32,2.808,NaN,NaN,NaN,NaN,NaN,210.488700,7.808,False
11,1,2010-04-23,64.84,2.795,NaN,NaN,NaN,NaN,NaN,210.439123,7.808,False
12,1,2010-04-30,67.41,2.780,NaN,NaN,NaN,NaN,NaN,210.389546,7.808,False
13,1,2010-05-07,72.55,2.835,NaN,NaN,NaN,NaN,NaN,210.339968,7.808,False
14,1,2010-05-14,74.78,2.854,NaN,NaN,NaN,NaN,NaN,210.337426,7.808,False
15,1,2010-05-21,76.44,2.826,NaN,NaN,NaN,NaN,NaN,210.617093,7.808,False
16,1,2010-05-28,80.44,2.759,NaN,NaN,NaN,NaN,NaN,210.896761,7.808,False
17,1,2010-06-04,80.69,2.705,NaN,NaN,NaN,NaN,NaN,211.176428,7.808,False
18,1,2010-06-11,80.43,2.668,NaN,NaN,NaN,NaN,NaN,211.456095,7.808,False
19,1,2010-06-18,84.11,2.637,NaN,NaN,NaN,NaN,NaN,211.453772,7.808,False
20,1,2010-06-25,84.34,2.653,NaN,NaN,NaN,NaN,NaN,211.338653,7.808,False
21,1,2010-07-02,80.91,2.669,NaN,NaN,NaN,NaN,NaN,211.223533,7.787,False
22,1,2010-07-09,80.48,2.642,NaN,NaN,NaN,NaN,NaN,211.108414,7.787,False
23,1,2010-07-16,83.15,2.623,NaN,NaN,NaN,NaN,NaN,211.100385,7.787,False
24,1,2010-07-23,83.36,2.608,NaN,NaN,NaN,NaN,NaN,211.235144,7.787,False
25,1,2010-07-30,81.84,2.640,NaN,NaN,NaN,NaN,NaN,211.369903,7.787,False
26,1,2010-08-06,87.16,2.627,NaN,NaN,NaN,NaN,NaN,211.504662,7.787,False
27,1,2010-08-13,87.00,2.692,NaN,NaN,NaN,NaN,NaN,211.639421,7.787,False
28,1,2010-08-20,86.65,2.664,NaN,NaN,NaN,NaN,NaN,211.603363,7.787,False
29,1,2010-08-27,85.22,2.619,NaN,NaN,NaN,NaN,NaN,211.567306,7.787,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8160,45,2013-01-04,32.87,3.592,1341.33,30325.14,8.93,35.85,3682.17,192.659622,8.625,False
8161,45,2013-01-11,38.78,3.611,3877.36,15559.85,3.81,152.18,2403.14,192.759980,8.625,False
8162,45,2013-01-18,41.45,3.605,14746.10,4071.06,4.02,483.58,1467.78,192.809507,8.625,False
8163,45,2013-01-25,26.49,3.583,3130.28,1362.10,0.20,332.68,1361.74,192.838701,8.625,False
8164,45,2013-02-01,34.92,3.615,14508.96,1092.53,827.90,26424.02,700.93,192.867895,8.625,False
8165,45,2013-02-08,28.99,3.753,53311.88,531.33,78.26,24823.94,3233.44,192.897089,8.625,True
8166,45,2013-02-15,35.87,3.814,9362.02,2017.68,0.36,5012.39,6411.71,192.943471,8.625,False
8167,45,2013-02-22,31.48,3.859,10781.51,2735.67,23.38,1516.76,3061.21,193.032822,8.625,False
8168,45,2013-03-01,39.72,3.890,6614.32,147.82,5.60,27.55,1668.95,193.122173,8.625,False
8169,45,2013-03-08,36.13,3.860,16382.54,88.67,34.62,3096.92,3486.91,193.211524,8.625,False
8170,45,2013-03-15,42.81,3.834,9867.03,NaN,11.08,912.87,1360.36,193.296277,8.625,False
8171,45,2013-03-22,36.55,3.800,11923.74,NaN,308.00,1764.47,1647.31,193.369533,8.625,False
8172,45,2013-03-29,40.68,3.784,5444.00,NaN,350.84,53.90,1722.11,193.442790,8.625,False
8173,45,2013-04-05,43.94,3.763,16427.83,5341.41,182.59,1523.83,1743.09,193.516047,8.335,False
8174,45,2013-04-12,57.39,3.724,8760.15,1713.11,21.08,1302.31,1380.74,193.589304,8.335,False
8175,45,2013-04-19,56.27,3.676,1399.81,39.89,44.38,60.83,1445.05,193.589304,8.335,False
8176,45,2013-04-26,50.64,3.615,1260.65,NaN,57.52,40.51,2476.18,193.589304,8.335,False
8177,45,2013-05-03,56.07,3.592,8345.40,6.00,92.96,3580.32,2242.24,NaN,NaN,False
8178,45,2013-05-10,58.86,3.583,4689.18,440.82,53.09,375.22,5738.20,NaN,NaN,False
8179,45,2013-05-17,60.59,3.614,4515.35,667.88,6.12,522.70,2541.62,NaN,NaN,False
8180,45,2013-05-24,67.11,3.627,3249.34,481.82,58.48,1183.23,1309.30,NaN,NaN,False
8181,45,2013-05-31,65.88,3.646,6474.49,411.38,77.06,9.38,4227.27,NaN,NaN,False
8182,45,2013-06-07,70.71,3.633,9977.82,744.29,80.00,4825.71,3597.34,NaN,NaN,False
8183,45,2013-06-14,70.01,3.632,2471.44,517.87,348.54,2612.33,3459.39,NaN,NaN,False
8184,45,2013-06-21,70.13,3.626,4989.34,385.31,178.56,2463.42,3117.94,NaN,NaN,False
8185,45,2013-06-28,76.05,3.639,4842.29,975.03,3.00,2449.97,3169.69,NaN,NaN,False
8186,45,2013-07-05,77.50,3.614,9090.48,2268.58,582.74,5797.47,1514.93,NaN,NaN,False
8187,45,2013-07-12,79.37,3.614,3789.94,1827.31,85.72,744.84,2150.36,NaN,NaN,False
8188,45,2013-07-19,82.84,3.737,2961.49,1047.07,204.19,363.00,1059.46,NaN,NaN,False
8189,45,2013-07-26,76.06,3.804,212.02,851.73,2.06,10.88,1864.57,NaN,NaN,False